# Generated by Django 5.2.6 on 2025-10-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disfraz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('cosplay', 'Cosplays y Personajes Famosos'), ('uniforme', 'Uniformes Profesionales'), ('creativo', 'Disfraces Creativos'), ('decoracion', 'Decoración y Exhibición')], max_length=100)),
                ('imagen', models.ImageField(upload_to='catalogo/')),
            ],
        ),
    ]
