# Generated by Django 5.2.6 on 2025-10-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disfraz',
            name='categoria',
            field=models.CharField(choices=[('cosplay', 'Cosplay y personajes famosos'), ('uniforme', 'Uniformes profesionales'), ('creativo', 'Disfraces personalizados y creativos'), ('decoracion', 'Decoración y exhibición')], max_length=20),
        ),
    ]
