# Generated by Django 5.2.6 on 2025-11-04 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_catalogoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogoitem',
            name='categoria',
            field=models.CharField(choices=[('cosplay', 'Cosplays y personajes famosos'), ('uniformes', 'Uniformes profesionales'), ('personalizados', 'Disfraces personalizados'), ('otros', 'Otros')], default='otros', max_length=50),
        ),
    ]
